@base_url=http://localhost:4030

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfMnVSRHRWcmdQekQzRzA0dzdzTDBDVkQ1T0xoIiwiaWF0IjoxNzQzMzY1NjM1LCJleHAiOjE3NDM0NTIwMzV9.oF8aXk0ENUXGLIV2LKh-n8btCpgTeq6GMsHkSGEwDoI

@api_key=aa5d9ce0-b6c5-4f5e-bbb4-f9c24abcef1f

@signature=9146729876fc7fcc6fd82ef979c658e7cbfd493d7f2df2032466cb1409e948f3
###
GET {{base_url}}

### register user
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "email":"test3@test.com",
    "password":"12345678"
}

### login user
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email":"kellytoroitich89@gmail.com",
    "password":"1234567"
}

### get users
GET {{base_url}}/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

### generate token
POST {{base_url}}/auth/generate-key
Content-Type: application/json
Authorization: Bearer {{token}}

### shorten url - remove auth headers
POST {{base_url}}/api/shorten
Content-Type: application/json
x-api-key: {{api_key}}
# Authorization: Bearer {{token}} 

{
    "original":"http://test.com" 
}

### redirect
GET {{base_url}}/url/cjibq

### get all stats
GET {{base_url}}/me/stats
x-api-key: {{api_key}}

### get stats
GET {{base_url}}/stats?shortId=00yxc
x-api-key: {{api_key}}

### post a url
GET {{base_url}}/api/user
Authorization: Bearer {{token}}


### testing webhooks - register the user in trackify
POST {{base_url}}/webhook/docx
Content-Type: application/json
x-webhook-signature:{{signature}}

{
    "event":"user.created",
    "data":{
        "userId":"user_2uRDtVrgPzD3G04w7sL0CVD5OLh",
        "email":"kellytoroitich89@gmail.com",
        "password":"1234567",
        "callbackUrl":"http://localhost:3000/api/webhooks/trackify"
    }
}


