@base_url=http://localhost:4030

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzMWNiNzUwLTMwNzctNDQ2ZS04MDA0LTI0YTY3OGYyYTcyOCIsImlhdCI6MTc0MzAxNzY5OCwiZXhwIjoxNzQzMTA0MDk4fQ.NdfMHXzdfGtyAxY676YLb1cGVLfP9Xkflu1CCWnrwDE

@api_key=793a61c6-b0bf-4ab2-bb93-d1d999010784

@signature=c153d04e276f415f2db05c56298f9861b1f428c5db4e296d6aa2af987a009de5
###
GET {{base_url}}

### register user
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "email":"test3@test.com",
    "password":"12345678"
}

### login user
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"123456"
}

### get users
GET {{base_url}}/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

### generate token
POST {{base_url}}/auth/generate-key
Content-Type: application/json
Authorization: Bearer {{token}}

### shorten url
POST {{base_url}}/api/shorten
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: Bearer {{token}}

{
    "original":"http://instagram.com" 
}

### redirect
GET {{base_url}}/url/cjibq

### get all stats
GET {{base_url}}/me/stats
x-api-key: {{api_key}}

### get stats
GET {{base_url}}/stats?shortId=00yxc
x-api-key: {{api_key}}

### post a url
GET {{base_url}}/api/user
Authorization: Bearer {{token}}


### testing webhooks
POST {{base_url}}/webhook/docx
Content-Type: application/json
x-webhook-signature:{{signature}}

{
    "event":"user.created",
    "data":{
        "userId":"431cb751-7730-446e-8006-24a678f2a728",
        "email":"kelly@gmail.com",
        "password":"1234567",
        "callbackUrl":"http://localhost:3000/api/webhook"
    }
}


